import {
  Backdrop,
  Box,
  Button,
  TextField,
  Typography,
  useTheme,
} from "@mui/material";
import { useState, useEffect } from "react";

function Search() {
  const theme = useTheme();

  const [searchTerm, setSearchTerm] = useState("");
  const [translations, setTranslations] = useState<string[]>([]);
  const [backdropState, setBackdropState] = useState(false);

  useEffect(() => {
    const allTranslations = [
      //Greetings
      "Hello - Hei",
      "Hi - Moi",
      "Good morning - Hyvää huomenta",
      "Good afternoon - Hyvää iltapäivää",
      "Good evening - Hyvää iltaa",
      "Good night - Hyvää yötä",
      "Goodbye - Näkemiin",
      "See you later - Nähdään myöhemmin",
      "See you soon - Nähdään pian",
      "Take care - Ole varovainen",
      "Have a good day - Hyvää päivänjatkoa",
      "Have a good trip - Hyvää matkaa",
      "Welcome - Tervetuloa",
      "How are you? - Mitä kuuluu?",
      "I'm fine, thank you - Kiitos hyvää",
      "Thank you - Kiitos",
      "You're welcome - Ole hyvä",
      "Excuse me - Anteeksi",
      "I'm sorry - Olen pahoillani",
      "Bless you - Terveydeksi",
      "Congratulations - Onneksi olkoon",
      "Happy birthday - Hyvää syntymäpäivää",
      "Happy new year - Hyvää uutta vuotta",
      "Merry Christmas - Hyvää joulua",
      "Good luck - Onnea",
      "Cheers - Kippis",
      "Bon appétit - Hyvää ruokahalua",
      "Get well soon - Pikaista paranemista",
      "I love you - Rakastan sinua",
      "I miss you - Minulla on ikävä sinua",
      "I need you - Tarvitsen sinua",
      "I want you - Haluan sinut",
      "I like you - Pidän sinusta",
      "I hate you - Vihaan sinua",
      "I'm happy - Olen onnellinen",
      "I'm sad - Olen surullinen",

      //Time
      "What time is it? - Paljonko kello on?",
      "It's one o'clock - Kello on yksi",
      "It's two o'clock - Kello on kaksi",
      "It's three o'clock - Kello on kolme",
      "It's four o'clock - Kello on neljä",
      "It's five o'clock - Kello on viisi",
      "It's six o'clock - Kello on kuusi",
      "It's seven o'clock - Kello on seitsemän",
      "It's eight o'clock - Kello on kahdeksan",
      "It's nine o'clock - Kello on yhdeksän",
      "It's ten o'clock - Kello on kymmenen",
      "It's eleven o'clock - Kello on yksitoista",
      "It's twelve o'clock - Kello on kaksitoista",
      "It's noon - Kello on keskipäivä",
      "It's midnight - Kello on keskiyö",
      "Morning - Aamu",
      "Afternoon - Iltapäivä",
      "Evening - Ilta",
      "Night - Yö",
      "Day - Päivä",
      "Week - Viikko",
      "Month - Kuukausi",
      "Year - Vuosi",
      "Today - Tänään",
      "Yesterday - Eilen",
      "Tomorrow - Huomenna",

      //Family
      "Family - Perhe",
      "Father - Isä",
      "Dad - Isä",
      "Mother - Äiti",
      "Mom - Äiti",
      "Parents - Vanhemmat",
      "Son - Poika",
      "Daughter - Tytär",
      "Brother - Veli",
      "Sister - Sisko",
      "Grandfather - Isoisä",
      "Grandpa - Isoisä",
      "Grandmother - Isoäiti",
      "Grandma - Isoäiti",
      "Grandparents - Isovanhemmat",
      "Uncle - Setä",
      "Aunt - Täti",
      "Cousin - Serkku",
      "Nephew - Veli poika",
      "Niece - Sisko tytär",
      "Husband - Mies",
      "Wife - Vaimo",
      "Spouse - Puoliso",

      //Colors
      "Color - Väri",
      "Red - Punainen",
      "Orange - Oranssi",
      "Yellow - Keltainen",
      "Green - Vihreä",
      "Blue - Sininen",
      "Purple - Violetti",
      "Pink - Pinkki",
      "Brown - Ruskea",
      "Black - Musta",
      "White - Valkoinen",
      "Gray - Harmaa",
      "Silver - Hopea",
      "Gold - Kulta",
      "Beige - Beige",
      "Rainbow - Sateenkaari",

      //Places
      "Place - Paikka",
      "Country - Maa",
      "City - Kaupunki",
      "Town - Kaupunki",
      "Village - Kylä",
      "Street - Katu",
      "Road - Tie",
      "Highway - Moottoritie",
      "Home - Koti",
      "House - Talo",
      "Apartment - Asunto",
      "Building - Rakennus",
      "School - Koulukoulu",
      "University - Yliopisto",
      "College - Korkeakoulu",
      "Library - Kirjasto",
      "Bookstore - Kirjakauppa",
      "Café - Kahvila",
      "Restaurant - Ravintola",
      "Bar - Baari",
      "Hotel - Hotelli",
      "Hospital - Sairaala",
      "Pharmacy - Apteekki",
      "Bank - Pankki",
      "Post office - Posti",
      "Store - Kauppa",
      "Supermarket - Supermarket",
      "Market - Markkinat",
      "Park - Puisto",
      "Beach - Ranta",
      "Lake - Järvi",
      "River - Joki",
      "Mountain - Vuori",
      "Forest - Metsä",
      "Garden - Puutarha",
      "Zoo - Eläintarha",
      "Museum - Museo",
      "Theater - Teatteri",
      "Cinema - Elokuvateatteri",
      "Stadium - Stadion",
      "Airport - Lentokenttä",
      "Train station - Rautatieasema",
      "Bus station - Linja-autoasema",

      //Food
      "Food - Ruoka",
      "Drink - Juoma",
      "Breakfast - Aamiainen",
      "Lunch - Lounas",
      "Dinner - Päivällinen",
      "Snack - Välipala",
      "Appetizer - Alkupala",
      "Main course - Pääruoka",
      "Dessert - Jälkiruoka",
      "Beverage - Juoma",
      "Water - Vesi",
      "Milk - Maito",
      "Tea - Tee",
      "Coffee - Kahvi",
      "Juice - Mehua",
      "Soda - Limonadi",
      "Beer - Olutta",
      "Wine - Viiniä",
      "Bread - Leipä",
      "Butter - Voi",
      "Cheese - Juusto",
      "Egg - Muna",
      "Rice - Riisi",
      "Pasta - Pasta",
      "Pizza - Pizza",

      //Clothing
      "Clothing - Vaatteet",
      "Shirt - Paita",
      "Blouse - Pusero",
      "T-shirt - T-paita",
      "Sweater - Neule",
      "Jacket - Takki",
      "Coat - Takki",
      "Dress - Mekko",
      "Skirt - Hame",
      "Pants - Housut",
      "Jeans - Farkut",
      "Shorts - Shortsit",
      "Socks - Sukat",
      "Shoes - Kengät",
      "Boots - Saappaat",
      "Hat - Hattu",
      "Gloves - Hanskat",
      "Scarf - Huivi",
      "Tie - Solmio",
      "Belt - Vyö",
      "Suit - Puku",
      "Dress - Puku",
      "Uniform - Univormu",
      "Swimsuit - Uimapuku",
      "Pajamas - Pyjama",
      "Underwear - Alusvaatteet",
      "Bra - Rintaliivit",
      "Panties - Pikkuhousut",
      "Sweatshirt - Collegepaita",
      "Raincoat - Sadetakki",
      "Umbrella - Sateenvarjo",
      "Sunglasses - Aurinkolasit",
      "Watch - Kello",
      "Jewelry - Korut",
      "Ring - Sormus",
      "Earrings - Korvakorut",
      "Necklace - Kaulakoru",
      "Bracelet - Rannekoru",
      "Anklet - Nilkkakoru",

      //Numbers
      "Zero - Nolla",
      "One - Yksi",
      "Two - Kaksi",
      "Three - Kolme",
      "Four - Neljä",
      "Five - Viisi",
      "Six - Kuusi",
      "Seven - Seitsemän",
      "Eight - Kahdeksan",
      "Nine - Yhdeksän",
      "Ten - Kymmenen",
      "Eleven - Yksitoista",
      "Twelve - Kaksitoista",
      "Thirteen - Kolmetoista",
      "Fourteen - Neljätoista",
      "Fifteen - Viisitoista",
      "Sixteen - Kuusitoista",
      "Seventeen - Seitsemäntoista",
      "Eighteen - Kahdeksantoista",
      "Nineteen - Yhdeksäntoista",
      "Twenty - Kaksikymmentä",

      //Days
      "Monday - Maanantai",
      "Tuesday - Tiistai",
      "Wednesday - Keskiviikko",
      "Thursday - Torstai",
      "Friday - Perjantai",
      "Saturday - Lauantai",
      "Sunday - Sunnuntai",
      "Week - Viikko",
      "Month - Kuukausi",
      "Year - Vuosi",
      "Today - Tänään",
      "Yesterday - Eilen",
      "Tomorrow - Huomenna",
      "Morning - Aamu",
      "Afternoon - Iltapäivä",
      "Evening - Ilta",
      "Night - Yö",
      "Day - Päivä",
      "Weekend - Viikonloppu",
      "Holiday - Loma",
      "Season - Vuodenaika",
      "Spring - Kevät",
      "Summer - Kesä",
      "Autumn - Syksy",
      "Winter - Talvi",
      "January - Tammikuu",
      "February - Helmikuu",
      "March - Maaliskuu",
      "April - Huhtikuu",

      // Phrase
      "How are you? - Mitä kuuluu?",
      "I'm fine, thank you - Kiitos hyvää",
      "What is your name? - Mikä sinun nimesi on?",
      "My name is... - Minun nimeni on...",
      "Where are you from? - Mistä olet kotoisin?",
      "I'm from... - Olen kotoisin...",
      "What time is it? - Paljonko kello on?",
      "Do you speak English? - Puhutko englantia?",
      "I don't understand - En ymmärrä",
      "I don't speak Finnish - En puhu suomea",
      "I don't know - En tiedä",
      "I'm sorry - Olen pahoillani",
      "I need help - Tarvitsen apua",
      "Can you help me? - Voitko auttaa minua?",
      "Where is the toilet? - Missä on vessa?",
      "How much is this? - Paljonko tämä maksaa?",
      "I would like... - Haluaisin...",
      "I want... - Haluan...",
      "I don't want... - En halua...",
      "I like... - Pidän...",
      "I don't like... - En pidä...",
      "I love... - Rakastan...",
      "I hate... - Vihaan...",
      "I am... - Olen...",
      "I'm not... - En ole...",
      "I can... - Voin...",
      "I can't... - En voi...",

      //Sentences
      "I am a student - Olen opiskelija",
      "I am a teacher - Olen opettaja",
      "I am a doctor - Olen lääkäri",
      "I am a nurse - Olen sairaanhoitaja",
      "I am a police officer - Olen poliisi",
      "I am a firefighter - Olen palomies",
      "I am a lawyer - Olen asianajaja",
      "I am a businessman - Olen liikemies",
      "I am a businesswoman - Olen liikenainen",
      "I am a chef - Olen kokki",
      "I am a waiter - Olen tarjoilija",
      "I am a waitress - Olen tarjoilija",
      "I am a pilot - Olen lentäjä",
      "I am a flight attendant - Olen lentoemäntä",

      //Greetings
      "Good morning, how are you? - Hyvää huomenta, mitä kuuluu?",
      "Good afternoon, nice to see you - Hyvää iltapäivää, mukava nähdä sinua",
      "Good evening, have a great night - Hyvää iltaa, mukavaa iltaa",
      "Good night, sweet dreams - Hyvää yötä, makeita unia",
      "Hello, nice to meet you - Hei, hauska tavata",
      "Hi, how's your day? - Moi, miten päiväsi on sujunut?",
      "See you tomorrow - Nähdään huomenna",
      "Take care of yourself - Huolehdi itsestäsi",
      "Nice to see you again - Mukava nähdä sinut taas",
      "Welcome back - Tervetuloa takaisin",
      "How's it going? - Miten menee?",
      "I hope you're doing well - Toivottavasti voit hyvin",

      //Expressions
      "I agree - Olen samaa mieltä",
      "I disagree - Olen eri mieltä",
      "Of course - Tietysti",
      "I don't mind - Ei haittaa",
      "I'm lost - Olen eksyksissä",
      "I'm confused - Olen hämmentynyt",
      "I'm hungry - Olen nälkäinen",
      "I'm thirsty - Olen janoinen",
      "I'm tired - Olen väsynyt",
      "I'm bored - Olen kyllästynyt",
      "I'm excited - Olen innoissani",
      "I'm scared - Olen peloissani",
      "I'm surprised - Olen yllättynyt",
      "I'm happy for you - Olen iloinen puolestasi",
      "I'm sorry to hear that - Olen pahoillani kuullessani sen",
      "I don't believe you - En usko sinua",
      "I trust you - Luotan sinuun",
      "I'm ready - Olen valmis",
      "I'm not ready - En ole valmis",
      "I'm in a hurry - Olen kiireinen",
      "I'm just kidding - Pilaan vain",
      "I'm just curious - Olen vain utelias",
      "I'm looking for... - Etsin...",
      "I'm thinking about... - Ajattelen...",
      "I'm dreaming of... - Unelmoin...",
      "I'm working on it - Työstän sitä",

      //Requests
      "Can you please help me? - Voitko auttaa minua, ole hyvä?",
      "Could you repeat that? - Voisitko toistaa sen?",
      "Please speak more slowly - Puhutko hitaammin, ole hyvä?",
      "Can you show me? - Voitko näyttää minulle?",
      "Could you explain? - Voisitko selittää?",
      "Please wait a moment - Odota hetki, ole hyvä",
      "Can you call a taxi? - Voisitko soittaa taksin?",
      "Please write it down - Kirjoita se ylös, ole hyvä",
      "Could you recommend a good restaurant? - Voisitko suositella hyvää ravintolaa?",
      "Can I have the bill, please? - Voinko saada laskun, ole hyvä?",
      "Please, don't do that - Älä tee sitä, ole hyvä",
      "Could you pass me the salt? - Voisitko antaa minulle suolan?",
      "Can I have a glass of water? - Voinko saada lasin vettä?",
      "Please, call me later - Soita minulle myöhemmin, ole hyvä",
      "Could you open the window? - Voisitko avata ikkunan?",
      "Can I use your phone? - Voinko käyttää puhelintasi?",
      "Please, come with me - Tule mukaani, ole hyvä",
      "Could you show me the way to the museum? - Voisitko näyttää minulle tien museoon?",

      //Emotions
      "I'm feeling happy - Tunnen itseni onnelliseksi",
      "I'm feeling sad - Tunnen itseni surulliseksi",
      "I'm feeling excited - Tunnen itseni innoissani",
      "I'm feeling anxious - Tunnen itseni levottomaksi",
      "I'm feeling grateful - Tunnen itseni kiitolliseksi",
      "I'm feeling angry - Tunnen itseni vihaiseksi",
      "I'm feeling lonely - Tunnen itseni yksinäiseksi",
      "I'm feeling tired - Tunnen itseni väsyneeksi",
      "I'm feeling confused - Tunnen itseni hämmentyneeksi",
      "I'm feeling optimistic - Tunnen itseni optimistiseksi",
      "I'm feeling proud - Tunnen itseni ylpeäksi",
      "I'm feeling bored - Tunnen itseni tylsistyneeksi",
      "I'm feeling worried - Tunnen itseni huolestuneeksi",
      "I'm feeling surprised - Tunnen itseni yllättyneeksi",
      "I'm feeling relieved - Tunnen itseni helpottuneeksi",
      "I'm feeling love - Tunnen rakkautta",

      //Questions
      "What do you think? - Mitä mieltä olet?",
      "What would you like to do? - Mitä haluaisit tehdä?",
      "How does that sound? - Miltä kuulostaa?",
      "Why did you do that? - Miksi teit niin?",
      "When will you be back? - Milloin palaat?",
      "Where are we going? - Minne olemme menossa?",
      "Who is coming with us? - Kuka tulee mukaan?",
      "How did it go? - Miten meni?",
      "What's the plan? - Mikä on suunnitelma?",
      "Is everything okay? - Onko kaikki hyvin?",
      "Would you like some help? - Haluaisitko hieman apua?",
      "Did you have a good day? - Oliko sinulla hyvä päivä?",
      "What's your favorite color? - Mikä on lempivärisi?",
      "What's your favorite food? - Mikä on lempiruokasi?",
      "Where is the best place to eat? - Missä on paras paikka syödä?",
      "How was your weekend? - Miten viikonloppusi meni?",
      "Have you ever been here before? - Oletko koskaan ollut täällä ennen?",
      "What are you thinking about? - Mitä ajattelet?",
      "Can you tell me more? - Voitko kertoa minulle lisää?",
      "When are you free? - Milloin sinulla on vapaata?",
      "What do you like to do for fun? - Mitä pidät hauskanasi tekemisestä?",
      "Would you like to go for a walk? - Haluaisitko mennä kävelylle?",
      "What's your favorite movie? - Mikä on lempielokuvasi?",
      "Can you recommend a good book? - Voitko suositella hyvää kirjaa?",
      "When is your birthday? - Milloin on syntymäpäiväsi?",
      "How do you feel today? - Miltä sinusta tuntuu tänään?",
      "Can I give you a hug? - Voinko halata sinua?",

      //Health
      "I'm feeling sick - Tunnen itseni sairaaksi",
      "I have a headache - Minulla on päänsärky",
      "I have a fever - Minulla on kuume",
      "My stomach hurts - Minulla on vatsakipu",
      "I have a cold - Minulla on flunssa",
      "I have a sore throat - Minulla on kurkkukipu",
      "I have a cough - Minulla on yskä",
      "I hurt my leg - Satutin jalkani",
      "I need to see a doctor - Minun täytyy mennä lääkäriin",
      "I need medicine - Tarvitsen lääkettä",
      "Can you help me find a pharmacy? - Voitko auttaa minua löytämään apteekin?",
      "I need to rest - Minun täytyy levätä",
      "Where is the nearest hospital? - Missä on lähin sairaala?",
      "Please call an ambulance - Soita ambulanssi, ole hyvä",
      "I have allergies - Minulla on allergioita",
      "I need to lie down - Minun täytyy mennä makuulle",
      "I have a toothache - Minulla on hammassärky",
      "I need a dentist - Tarvitsen hammaslääkärin",

      //Shopping
      "I'm looking for a gift - Etsin lahjaa",
      "How much does this cost? - Paljonko tämä maksaa?",
      "Do you have this in a different color? - Onko tätä eri värissä?",
      "I would like to buy this - Haluaisin ostaa tämän",
      "Can I try this on? - Voinko sovittaa tätä?",
      "Do you have a fitting room? - Onko teillä sovituskoppeja?",
      "Where can I find...? - Missä voin löytää...?",
      "I'm just browsing - Selailen vain",
      "I'm looking for something specific - Etsin jotain tiettyä",
      "Is there a discount? - Onko alennusta?",
      "Do you accept credit cards? - Hyväksyttekö luottokortit?",
      "I'll take it - Otan sen",
      "Can I return this? - Voinko palauttaa tämän?",
      "I'm not sure, I'll think about it - En ole varma, mietin asiaa",
      "I'm looking for a size... - Etsin kokoa...",
      "I'm looking for a present for my friend - Etsin lahjaa ystävälleni",
      "I need a new pair of shoes - Tarvitsen uudet kengät",
      "I'm shopping for clothes - Ostan vaatteita",
      "I'm shopping for groceries - Ostan ruokaa",
      "I'm shopping for souvenirs - Ostan matkamuistoja",
      "I'm looking for a book - Etsin kirjaa",
      "I'm looking for a toy for my child - Etsin lelua lapselleni",

      //Travel
      "I'm going on vacation - Lähden lomalle",
      "I'm going on a business trip - Menen työmatkalle",
      "I need to book a flight - Minun täytyy varata lento",
      "I need to book a hotel - Minun täytyy varata hotelli",
      "I need a rental car - Tarvitsen vuokra-auton",
      "I'm lost, can you help me find my way? - Olen eksyksissä, voitko auttaa minua löytämään tieni?",
      "I'm looking for a tourist attraction - Etsin turistinähtävyyttä",
      "Where is the nearest bus stop? - Missä on lähin bussipysäkki?",
      "Is there a train station nearby? - Onko täällä lähellä junastasemia?",
      "Which bus goes to the city center? - Mikä bussi menee keskustaan?",
      "I need a map - Tarvitsen kartan",
      "I want to visit museums - Haluan vierailla museoissa",
      "I want to try local food - Haluan maistaa paikallista ruokaa",
      "I'm here for sightseeing - Olen täällä nähtävyyksien vuoksi",
      "I'm looking for a good restaurant - Etsin hyvää ravintolaa",
      "Is there a guided tour available? - Onko opastettuja kierroksia saatavilla?",
      "I want to take photos - Haluan ottaa valokuvia",
      "Where can I buy tickets? - Mistä voin ostaa liput?",
      "I need to find a taxi - Minun täytyy löytää taksi",
      "I want to rent a bike - Haluan vuokrata pyörän",
      "I'm going to the airport - Menen lentokentälle",
      "I want to buy some souvenirs - Haluan ostaa matkamuistoja",
      "I'm going to the beach - Menen rannalle",
      "I'm going hiking - Menen patikoimaan",
      "I'm going skiing - Menen laskettelemaan",
      "I want to go shopping - Haluan mennä ostoksille",
      "I need to exchange currency - Minun täytyy vaihtaa valuuttaa",
      "I want to visit historical sites - Haluan vierailla historiallisilla paikoilla",
      "I'm going on a cruise - Menen risteilylle",
      "I want to go scuba diving - Haluan mennä sukellukselle",
      "I'm going to the mountains - Menen vuorille",

      //Work
      "I have a meeting - Minulla on kokous",
      "I have a presentation - Minulla on esitys",
      "I have a deadline - Minulla on määräaika",
      "I have a lot of work to do - Minulla on paljon töitä",
      "I need to finish this report - Minun täytyy saada tämä raportti valmiiksi",
      "I have an appointment - Minulla on tapaaminen",
      "I need to make a phone call - Minun täytyy soittaa puhelu",
      "I need to send an email - Minun täytyy lähettää sähköposti",
      "I have a business trip - Minulla on työmatka",
      "I need to prepare for a meeting - Minun täytyy valmistautua kokoukseen",
      "I have to work late - Minun täytyy tehdä töitä myöhään",
      "I have a work event - Minulla on työtilaisuus",
      "I have to give a presentation - Minun täytyy pitää esitys",
      "I need to hire a new employee - Minun täytyy palkata uusi työntekijä",
      "I have to attend a conference - Minun täytyy osallistua konferenssiin",
      "I have to write a report - Minun täytyy kirjoittaa raportti",
      "I need to schedule a meeting - Minun täytyy aikatauluttaa kokous",
      "I have to review these documents - Minun täytyy tarkistaa nämä asiakirjat",
      "I have to organize this event - Minun täytyy järjestää tämä tilaisuus",
      "I have to create a presentation - Minun täytyy luoda esitys",
      "I have to attend a training session - Minun täytyy osallistua koulutukseen",
      "I need to analyze these data - Minun täytyy analysoida nämä tiedot",
      "I have to travel for work - Minun täytyy matkustaa työn vuoksi",
      "I have to interview a candidate - Minun täytyy haastatella ehdokasta",
      "I have to make a decision - Minun täytyy tehdä päätös",

      //Technology
      "I have a smartphone - Minulla on älypuhelin",
      "I need to charge my laptop - Minun täytyy ladata kannettava tietokoneeni",
      "I have to update my software - Minun täytyy päivittää ohjelmani",
      "I need to reset my password - Minun täytyy nollata salasanani",
      "I have to install new software - Minun täytyy asentaa uusi ohjelma",
      "I need to fix my printer - Minun täytyy korjata tulostimeni",
      "I have to back up my files - Minun täytyy varmuuskopioida tiedostoni",
      "I need to set up my email - Minun täytyy asettaa sähköpostini",
      "I have to learn how to use this app - Minun täytyy oppia käyttämään tätä sovellusta",
      "I need to update my website - Minun täytyy päivittää verkkosivuni",
      "I have to buy a new computer - Minun täytyy ostaa uusi tietokone",
      "I need to fix my wifi - Minun täytyy korjata wifi-yhteyteni",
      "I have to download this file - Minun täytyy ladata tämä tiedosto",
      "I need to create a backup plan - Minun täytyy luoda varasuunnitelma",
      "I have to learn how to code - Minun täytyy oppia koodaamaan",
      "I need to upgrade my phone - Minun täytyy päivittää puhelimeni",
      "I have to fix my camera - Minun täytyy korjata kamerani",
      "I need to organize my files - Minun täytyy järjestää tiedostoni",
      "I have to delete old emails - Minun täytyy poistaa vanhat sähköpostit",
      "I need to troubleshoot this problem - Minun täytyy ratkaista tämä ongelma",
      "I have to create a new password - Minun täytyy luoda uusi salasana",
      "I need to protect my data - Minun täytyy suojata tietoni",
      "I have to learn how to use social media - Minun täytyy oppia käyttämään sosiaalista mediaa",
      "I need to create a budget for tech expenses - Minun täytyy luoda budjetti teknisille kuluille",

      //Nature
      "I love the outdoors - Rakastan ulkoilmaa",
      "I enjoy hiking in the mountains - Nautin patikoimisesta vuorilla",
      "I like to swim in the lake - Tykkään uida järvessä",
      "I love the smell of fresh flowers - Rakastan tuoretuoksuisia kukkia",
      "I enjoy watching the sunset - Nautin auringonlaskun katsomisesta",
      "I like to listen to the sound of the ocean - Tykkään kuunnella meren ääntä",
      "I love camping in the forest - Rakastan leiriytymistä metsässä",
      "I enjoy picnics in the park - Nautin piknikistä puistossa",
      "I like to watch birds - Tykkään tarkkailla lintuja",
      "I love the sound of rain - Rakastan sateen ääntä",
      "I enjoy gardening - Nautin puutarhanhoidosta",
      "I like to go fishing - Tykkään kalastaa",
      "I love the colors of autumn leaves - Rakastan syksyn lehtien värejä",
      "I enjoy collecting seashells - Nautin simpukoiden keräämisestä",
      "I like to go for walks in nature - Tykkään käydä kävelyillä luonnossa",
      "I love the smell of pine trees - Rakastan mäntyjen tuoksua",
      "I enjoy watching the stars at night - Nautin tähtien katsomisesta yöllä",
      "I like to take photos of landscapes - Tykkään ottaa valokuvia maisemista",
      "I love the feeling of sand between my toes - Rakastan hiekkaa varpaissani",
      "I enjoy watching wildlife - Nautin villieläinten tarkkailusta",
      "I like to go rock climbing - Tykkään kiipeillä kallioilla",
      "I love the sound of birds singing - Rakastan lintujen laulua",
      "I enjoy watching the clouds - Nautin pilvien tuijottelusta",
      "I like to go biking in the countryside - Tykkään pyöräillä maaseudulla",
      "I love the beauty of a snow-covered landscape - Rakastan lumipeitteisen maiseman kauneutta",
      "I enjoy picking fresh berries - Nautin tuoreiden marjojen poimimisesta",

      //Sports
      "I play soccer - Pelaan jalkapalloa",
      "I love to swim - Rakastan uimista",
      "I enjoy running in the park - Nautin juoksemisesta puistossa",
      "I like to play tennis - Tykkään pelata tennistä",
      "I'm a fan of basketball - Olen koripallon fani",
      "I love to ski - Rakastan hiihtämistä",
      "I enjoy playing golf - Nautin golfin pelaamisesta",
      "I like to go hiking - Tykkään patikoinnista",
      "I'm a fan of baseball - Olen baseballin fani",
      "I love to dance - Rakastan tanssimista",
      "I enjoy yoga - Nautin joogasta",
      "I like to go cycling - Tykkään pyöräilystä",
      "I play volleyball - Pelaan lentopalloa",
      "I love to surf - Rakastan surffausta",
      "I enjoy rock climbing - Nautin kiipeilystä",
      "I like to go skateboarding - Tykkään skeittaamisesta",
      "I play badminton - Pelaan sulkapalloa",
      "I love to go camping - Rakastan leiriytymistä",
      "I enjoy playing table tennis - Nautin pöytätenniksen pelaamisesta",
      "I like to go horseback riding - Tykkään ratsastaa",
      "I play chess - Pelaan shakkia",
      "I love to go fishing - Rakastan kalastusta",
      "I enjoy playing pool - Nautin biljardin pelaamisesta",
      "I like to go bowling - Tykkään keilata",
      "I play cricket - Pelaan krikettiä",
      "I love to go kayaking - Rakastan kajakkiharrastusta",

      //Food and Drink
      "I'm hungry - Olen nälkäinen",
      "I'm thirsty - Olen janoinen",
      "I love pizza - Rakastan pizzaa",
      "I enjoy drinking coffee - Nautin kahvin juomisesta",
      "I like to eat pasta - Tykkään syödä pastaa",
      "I'm craving chocolate - Minulla tekee mieli suklaata",
      "I love to eat ice cream - Rakastan jäätelön syömistä",
      "I enjoy drinking tea - Nautin teen juomisesta",
      "I like to eat sushi - Tykkään syödä sushia",
      "I'm a fan of burgers - Olen hampurilaisten fani",
      "I love to eat tacos - Rakastan tacojen syömistä",
      "I enjoy drinking smoothies - Nautin smoothieiden juomisesta",
      "I like to eat Indian food - Tykkään syödä intialaista ruokaa",
      "I'm craving a sandwich - Minulla tekee mieli voileipää",
      "I love to eat Chinese food - Rakastan kiinalaista ruokaa",
      "I enjoy drinking beer - Nautin oluen juomisesta",
      "I like to eat Thai food - Tykkään syödä thaimaalaista ruokaa",
      "I'm a fan of steak - Olen pihvin fani",
      "I love to eat burgers - Rakastan hampurilaisia",
      "I enjoy drinking wine - Nautin viinin juomisesta",
      "I like to eat Mexican food - Tykkään syödä meksikolaista ruokaa",
      "I'm craving a salad - Minulla tekee mieli salaattia",
      "I love to eat seafood - Rakastan äyriäisiä",
      "I enjoy drinking cocktails - Nautin drinkkien juomisesta",
      "I like to eat Korean food - Tykkään syödä korealaista ruokaa",
      "I'm a fan of BBQ - Olen BBQ:n fani",
      "I love to eat Italian food - Rakastan italialaista ruokaa",
      "I enjoy drinking fruit juice - Nautin hedelmämehujen juomisesta",
      "I like to eat Greek food - Tykkään syödä kreikkalaista ruokaa",
      "I'm craving a burger - Minulla tekee mieli hampurilaista",
      "I love to eat Japanese food - Rakastan japanilaista ruokaa",
      "I enjoy drinking iced tea - Nautin jääteen juomisesta",
      "I like to eat Vietnamese food - Tykkään syödä vietnamilaista ruokaa",
      "I'm a fan of hot pot - Olen hot potin fani",
      "I love to eat Lebanese food - Rakastan libanonilaista ruokaa",
    ];

    const results = allTranslations.filter((translation) =>
      translation.toLowerCase().includes(searchTerm.toLowerCase())
    );

    setTranslations(results);
  }, [searchTerm]);

  const handleSearch = () => {
    setBackdropState(true);
  };

  return (
    <Box
      sx={{
        // color: "white",
        pb: 5,
        display: "flex",
        height: "10vh",
        justifyContent: "space-between",
      }}
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          marginBottom: "1rem",
        }}
      >
        <TextField
          sx={{
            flex: 1,
            marginRight: "1rem",
            backgroundColor: "white",
            color: "black",
            borderRadius: "8px",
            zIndex: 2,
          }}
          placeholder="Search..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          onKeyPress={(e) => {
            if (e.key === "Enter") {
              handleSearch();
            }
          }}
        />
        <Button
          sx={{
            backgroundColor: "white",
            color: "black",
            zIndex: 2,
            borderRadius: "8px",
            "&:hover": {
              backgroundColor: "white",
              opacity: 0.5,
              border: "none",
            },
          }}
          onClick={handleSearch}
        >
          Search
        </Button>
      </Box>
      <Backdrop open={backdropState} sx={{ zIndex: 1 }}>
        <Box>
          <Box
            sx={{
              height: "50vh",
              width: "90vw",
              backgroundColor: "#147e93",
              color: "white",
              p: 2,
              border: "solid 3px #4eb6b0",
              borderRadius: "8px",

              overflowY: "scroll",
              overflowX: "hide",

              "&::-webkit-scrollbar": {
                width: "0.4em",
              },
              "&::-webkit-scrollbar-track": {
                background: theme.palette.background.default,
              },
              "&::-webkit-scrollbar-thumb": {
                backgroundColor: "black",
                borderRadius: "0 8px 8px 0",
              },
              "&::-webkit-scrollbar-thumb:hover": {
                background: theme.palette.text.primary,
              },
            }}
          >
            {translations.map((translation, index) => (
              <Typography
                sx={{ pt: 2, pb: 2, borderBottom: "1px solid black" }}
                key={index}
              >
                {translation}
              </Typography>
            ))}
          </Box>
          <Button
            sx={{
              backgroundColor: "white",
              color: "black",
              mt: 3,
              borderRadius: "8px",
            }}
            onClick={() => setBackdropState(false)}
          >
            Close Search
          </Button>
        </Box>
      </Backdrop>
    </Box>
  );
}

export default Search;
